name: action
on:
  pull_request:
    types: [opened]
jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  python3 echo.py < ${{ github.event_path }}
