name: auto label 
on:
  pull_request:
    types: [opened]
jobs:
  label-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  python3 label.py ${{ github.event_path }}
