name: add-approve
on:
  pull_request:
    types: [opened]
jobs:
  add-approve:
    runs-on: self-hosted
    steps:
      - run: cd /home/vincent/programmers/.github/workflows/script && python3 add-approve.py ${{ github.event_path }}
