name: remove-merge
on:
  pull_request:
    types: [closed]
jobs:
  remove-merge:
    runs-on: self-hosted
    steps:
      - run: cd /home/vincent/programmers/.github/workflows/script && python3 remove-merge.py ${{ github.event_path }}
