name: remove-sender
on:
  pull_request_review:
    types: [submitted]
jobs:
  remove-sender:
    runs-on: self-hosted
    steps:
      - run: cat ${{ github.event_path }}
      - run: cd /home/vincent/programmers/.github/workflows/script && python3 remove-sender.py ${{ github.event_path }}
