name: remove-reviewer
on:
  pull_request:
    types: [review_request_removed]
jobs:
  remove-reviewer:
    runs-on: self-hosted
    steps:
      - run: cd /home/vincent/programmers/.github/workflows/script && python3 remove-reviewer.py ${{ github.event_path }}
